# -*- coding: utf-8 -*-
import sys

from PyQt5 import QtGui, QtWidgets
from img import *
from readConfig import BASE_DIR


# Form implementation generated from reading ui file 'adb_beifen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 597)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{BASE_DIR / 'logo48.png'}"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
                                 "    background-color: white;\n"
                                 "    color: rgb(106, 106, 106);\n"
                                 "}\n"
                                 "QPushButton{\n"
                                 "    color: rgb(106, 106, 106);\n"
                                 "    selection-color: rgb(201, 216, 255);\n"
                                 "    height:21px;\n"
                                 "    border:1px solid rgb(158, 158, 158);\n"
                                 "    border-radius:6px;\n"
                                 "    padding:0px 3px;\n"
                                 "    }\n"
                                 "QLineEdit{\n"
                                 "    border:1px solid gray;\n"
                                 "    height:21px;\n"
                                 "    border-radius:6px;\n"
                                 "    padding:0px 3px;\n"
                                 "    background: transparent;\n"
                                 "    }\n"
                                 "QPushButton:hover{\n"
                                 "    font-weight:700;\n"
                                 "    color:white;\n"
                                 "    border-color:rgb(188, 201, 244);\n"
                                 "    background-color: rgb(111, 172, 236);\n"
                                 "    }\n"
                                 "QPushButton:pressed{\n"
                                 "    font-weight:700;\n"
                                 "    border-color:rgb(188, 201, 200);\n"
                                 "    background-color: rgb(188, 201, 200);\n"
                                 "    }\n"
                                 "QScrollBar:vertical {\n"
                                 "    width: 8px;\n"
                                 "    background:rgba(0, 0, 0, 0%);\n"
                                 "    border-radius:4px;\n"
                                 "    border:none;\n"
                                 "}\n"
                                 "QScrollBar:handle:vertical{\n"
                                 "    border-radius:4px;\n"
                                 "    width: 8px;\n"
                                 "    background:rgba(0, 0, 0, 25%);\n"
                                 "}\n"
                                 "QScrollBar:handle:vertical:hover\n"
                                 "{\n"
                                 "    width:8px;\n"
                                 "    background:rgba(0, 0, 0, 50%);\n"
                                 "    border-radius:4px;\n"
                                 "    min-height:20;\n"
                                 "}\n"
                                 "QScrollBar:add-line:vertical\n"
                                 "{\n"
                                 "    height:0px;\n"
                                 "    width:0px;\n"
                                 "    subcontrol-position:bottom;\n"
                                 "}\n"
                                 "QScrollBar:sub-line:vertical\n"
                                 "{\n"
                                 "    height:0px;\n"
                                 "    width:0px;\n"
                                 "    subcontrol-position:top;\n"
                                 "}\n"
                                 " QMenu {\n"
                                 " }\n"
                                 "\n"
                                 " QMenu::item {\n"
                                 "    \n"
                                 "    background-color: transparent;\n"
                                 "    padding:5px 45px;\n"
                                 "    border-radius:6px;\n"
                                 "    margin:0px 0px;\n"
                                 "\n"
                                 " }\n"
                                 "\n"
                                 " QMenu::item:selected {\n"
                                 "     background-color: #e8e8e8;\n"
                                 "\n"
                                 " }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(270, 16777215))
        self.groupBox_3.setStyleSheet("            QGroupBox#groupBox_3{\n"
                                      "                 border:1px solid gray;\n"
                                      "                margin-top:0.5em;\n"
                                      "                 border-radius:10px;\n"
                                      "                 padding:0px;\n"
                                      "                }\n"
                                      "            QGroupBox::title {\n"
                                      "                subcontrol-origin: margin;\n"
                                      "                subcontrol-position: top left;\n"
                                      "                left:10px;\n"
                                      "                }")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setEnabled(True)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("QComboBox{\n"
                                    "    combobox-popup: 0;\n"
                                    "    border-style:none;\n"
                                    "    color: rgb(106, 106, 106);\n"
                                    "    height:21px;\n"
                                    "    border:1px solid rgb(158, 158, 158);\n"
                                    "    border-radius:6px;\n"
                                    "    padding:0px 3px;\n"
                                    "    background: white;\n"
                                    "    }\n"
                                    "\n"
                                    "QComboBox:drop-down {\n"
                                    "    width:0px;\n"
                                    "    border: none;\n"
                                    "    subcontrol-position: right center;\n"
                                    "    subcontrol-origin: padding;\n"
                                    "    }\n"
                                    "QComboBox QAbstractItemView{\n"
                                    "    outline: 0px;\n"
                                    "    border:1px solid rgb(158, 158, 158);\n"
                                    "    border-radius: 6px;\n"
                                    "    background-color: #FFFFFF;\n"
                                    "    }\n"
                                    "QComboBox QAbstractItemView::item {\n"
                                    "    color: rgb(106, 106, 106);\n"
                                    "    min-height: 23px; \n"
                                    "    border-radius:10px;\n"
                                    "    margin:3px 0px 3px 0px;\n"
                                    "    }\n"
                                    "QComboBox QAbstractScrollArea QScrollBar:vertical {\n"
                                    "    width: 8px;\n"
                                    "    border:none;\n"
                                    "    border-radius:4px;\n"
                                    "}\n"
                                    "QComboBox QAbstractScrollArea QScrollBar:handle:vertical{\n"
                                    "    border-radius:4px;\n"
                                    "    width: 8px;\n"
                                    "    background:gray;\n"
                                    "}\n"
                                    "QComboBox QAbstractItemView::item:selected{\n"
                                    "    color:white;\n"
                                    "    background-color: rgb(111, 172, 236);\n"
                                    "    }")
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget.setEnabled(True)
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.listWidget.setStyleSheet("            QListWidget{\n"
                                      "                outline:0px;\n"
                                      "                color: rgb(106, 106, 106);\n"
                                      "                border:none;\n"
                                      "                border-radius:5px;\n"
                                      "                padding:5px -5px 5px -5px;\n"
                                      "                background: transparent;\n"
                                      "            }\n"
                                      "            QListWidget::item\n"
                                      "                {\n"
                                      "                    color: rgb(106, 106, 106);\n"
                                      "                    min-height: 25px; \n"
                                      "                    border-radius:10px;\n"
                                      "                    margin:3px 0px 3px 0px;\n"
                                      "                }\n"
                                      "            QListWidget::item:hover\n"
                                      "                {\n"
                                      "                    color:white;\n"
                                      "                    background-color: rgb(111, 172, 236);\n"
                                      "                }\n"
                                      "            QListWidget::item:selected\n"
                                      "                {\n"
                                      "                    color:white;\n"
                                      "                    background-color: rgb(96, 193, 0);\n"
                                      "                }")
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setAutoScrollMargin(16)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setStyleSheet("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_16.addWidget(self.groupBox_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("            QTabWidget{\n"
                                     "                    background-color:transparent;\n"
                                     "            }\n"
                                     "            QTabWidget::pane{\n"
                                     "                        border:none;\n"
                                     "                        padding: 0px;\n"
                                     "            }\n"
                                     "            QTabWidget::tab-bar{alignment:left;}\n"
                                     "            QTabBar::tab{\n"
                                     "                color: rgb(106, 106, 106);\n"
                                     "                border-radius:8px;\n"
                                     "                            }\n"
                                     "            QTabBar::tab:hover{\n"
                                     "                color:white;\n"
                                     "                background-color: rgb(111, 172, 236);\n"
                                     "                            }\n"
                                     "            QTabBar::tab:selected{\n"
                                     "                            border-color: rgb(255, 115, 15);\n"
                                     "                            background:rgb(255, 115, 15);\n"
                                     "                            color:white;\n"
                                     "                            }\n"
                                     "\n"
                                     "            QTabBar::tab{width:80px}\n"
                                     "            QTabBar::tab{height:20px}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_15.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setStyleSheet("            QGroupBox#groupBox{\n"
                                    "                 border:1px solid gray;\n"
                                    "                margin-top: 0.5em;\n"
                                    "                 border-radius:10px;\n"
                                    "                 padding:0px;\n"
                                    "                }\n"
                                    "            QGroupBox::title {\n"
                                    "                subcontrol-origin: margin;\n"
                                    "                subcontrol-position: top left;\n"
                                    "                left:10px;\n"
                                    "                }")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setToolTip("")
        self.pushButton.setStyleSheet("")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setAcceptDrops(True)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setAcceptDrops(True)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setAcceptDrops(True)
        self.pushButton_11.setAutoDefault(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_7.addWidget(self.pushButton_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setAcceptDrops(True)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setAcceptDrops(True)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setAcceptDrops(True)
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setAcceptDrops(True)
        self.pushButton_13.setAutoDefault(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_6.addWidget(self.pushButton_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_5.addWidget(self.pushButton_17)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setAcceptDrops(True)
        self.pushButton_14.setAutoDefault(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setAcceptDrops(True)
        self.pushButton_15.setAutoDefault(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_5.addWidget(self.pushButton_15)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_20.addWidget(self.lineEdit_2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_17.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_17.addWidget(self.pushButton_20)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21.addLayout(self.verticalLayout_3)
        self.horizontalLayout_15.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_14.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setStyleSheet("\n"
                                      "            QGroupBox#groupBox_4{\n"
                                      "                 border:1px solid gray;\n"
                                      "                margin-top: 0.5em;\n"
                                      "                 border-radius:10px;\n"
                                      "                 padding:0px;\n"
                                      "                }\n"
                                      "            QGroupBox::title {\n"
                                      "                subcontrol-origin: margin;\n"
                                      "                subcontrol-position: top left;\n"
                                      "                left:10px;\n"
                                      "                }\n"
                                      "            QComboBox{\n"
                                      "                color: rgb(106, 106, 106);\n"
                                      "                border:1px solid rgb(158, 158, 158);\n"
                                      "                border-radius:5px;\n"
                                      "                padding:0px 5px 0px 5px;\n"
                                      "                background: transparent;\n"
                                      "                }\n"
                                      "            QCheckBox{\n"
                                      "                }\n"
                                      "            QCheckBox::indicator\n"
                                      "                {\n"
                                      "                }\n"
                                      "            QCheckBox::indicator:unchecked\n"
                                      "                {\n"
                                      "                }\n"
                                      "            QCheckBox::indicator:checked\n"
                                      "                {\n"
                                      "                }")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_19.setContentsMargins(5, 6, 5, 5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(7)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.package_apk = QtWidgets.QLineEdit(self.groupBox_4)
        self.package_apk.setMinimumSize(QtCore.QSize(0, 0))
        self.package_apk.setObjectName("package_apk")
        self.horizontalLayout_13.addWidget(self.package_apk)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.seed = QtWidgets.QLineEdit(self.groupBox_4)
        self.seed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.seed.setObjectName("seed")
        self.horizontalLayout_9.addWidget(self.seed)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.throttle = QtWidgets.QLineEdit(self.groupBox_4)
        self.throttle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.throttle.setText("")
        self.throttle.setObjectName("throttle")
        self.horizontalLayout_9.addWidget(self.throttle)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.level = QtWidgets.QLineEdit(self.groupBox_4)
        self.level.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.level.setObjectName("level")
        self.horizontalLayout_9.addWidget(self.level)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.event_num = QtWidgets.QLineEdit(self.groupBox_4)
        self.event_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.event_num.setObjectName("event_num")
        self.horizontalLayout_9.addWidget(self.event_num)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_18.setStretch(0, 2)
        self.horizontalLayout_18.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.crashes = QtWidgets.QCheckBox(self.groupBox_4)
        self.crashes.setMinimumSize(QtCore.QSize(10, 0))
        self.crashes.setChecked(True)
        self.crashes.setObjectName("crashes")
        self.horizontalLayout_10.addWidget(self.crashes)
        self.timeouts = QtWidgets.QCheckBox(self.groupBox_4)
        self.timeouts.setMinimumSize(QtCore.QSize(10, 0))
        self.timeouts.setChecked(True)
        self.timeouts.setObjectName("timeouts")
        self.horizontalLayout_10.addWidget(self.timeouts)
        self.security_exceptions = QtWidgets.QCheckBox(self.groupBox_4)
        self.security_exceptions.setMinimumSize(QtCore.QSize(10, 0))
        self.security_exceptions.setChecked(True)
        self.security_exceptions.setObjectName("security_exceptions")
        self.horizontalLayout_10.addWidget(self.security_exceptions)
        self.kill_error = QtWidgets.QCheckBox(self.groupBox_4)
        self.kill_error.setMinimumSize(QtCore.QSize(10, 0))
        self.kill_error.setChecked(True)
        self.kill_error.setObjectName("kill_error")
        self.horizontalLayout_10.addWidget(self.kill_error)
        self.native_crashes = QtWidgets.QCheckBox(self.groupBox_4)
        self.native_crashes.setMinimumSize(QtCore.QSize(10, 0))
        self.native_crashes.setChecked(True)
        self.native_crashes.setObjectName("native_crashes")
        self.horizontalLayout_10.addWidget(self.native_crashes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.touch = QtWidgets.QLineEdit(self.groupBox_4)
        self.touch.setObjectName("touch")
        self.horizontalLayout_11.addWidget(self.touch)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.motion = QtWidgets.QLineEdit(self.groupBox_4)
        self.motion.setObjectName("motion")
        self.horizontalLayout_11.addWidget(self.motion)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.pinchzoom = QtWidgets.QLineEdit(self.groupBox_4)
        self.pinchzoom.setObjectName("pinchzoom")
        self.horizontalLayout_11.addWidget(self.pinchzoom)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.trackball = QtWidgets.QLineEdit(self.groupBox_4)
        self.trackball.setObjectName("trackball")
        self.horizontalLayout_11.addWidget(self.trackball)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_16.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_11.addWidget(self.pushButton_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.rotation = QtWidgets.QLineEdit(self.groupBox_4)
        self.rotation.setObjectName("rotation")
        self.horizontalLayout_12.addWidget(self.rotation)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.majornav = QtWidgets.QLineEdit(self.groupBox_4)
        self.majornav.setObjectName("majornav")
        self.horizontalLayout_12.addWidget(self.majornav)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.syskeys = QtWidgets.QLineEdit(self.groupBox_4)
        self.syskeys.setObjectName("syskeys")
        self.horizontalLayout_12.addWidget(self.syskeys)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.appswitch = QtWidgets.QLineEdit(self.groupBox_4)
        self.appswitch.setObjectName("appswitch")
        self.horizontalLayout_12.addWidget(self.appswitch)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_12.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        self.horizontalLayout_14.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("            QGroupBox#groupBox_2{\n"
                                      "                 border:1px solid gray;\n"
                                      "                margin-top: 0.5em;\n"
                                      "                 border-radius:10px;\n"
                                      "                 padding:0px;\n"
                                      "                }\n"
                                      "            QTextBrowser{\n"
                                      "                border:none;\n"
                                      "                padding:0px;\n"
                                      "                }\n"
                                      "            QGroupBox::title {\n"
                                      "                subcontrol-origin: margin;\n"
                                      "                subcontrol-position: top left;\n"
                                      "                left:10px;\n"
                                      "                }")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(2, 6, 2, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setBold(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setAcceptDrops(True)
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setAcceptDrops(True)
        self.pushButton_10.setAutoDefault(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setAcceptDrops(True)
        self.pushButton_12.setAutoDefault(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_16.addLayout(self.verticalLayout_5)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADB工具"))
        self.groupBox_3.setTitle(_translate("MainWindow", "设备"))
        self.pushButton_3.setText(_translate("MainWindow", "刷新"))
        self.pushButton_18.setText(_translate("MainWindow", "刷新"))
        self.groupBox.setTitle(_translate("MainWindow", "adb操作"))
        self.pushButton.setText(_translate("MainWindow", "日志"))
        self.pushButton_5.setText(_translate("MainWindow", "截图"))
        self.pushButton_6.setText(_translate("MainWindow", "录屏"))
        self.pushButton_11.setText(_translate("MainWindow", "投屏"))
        self.pushButton_2.setText(_translate("MainWindow", "安装apk"))
        self.pushButton_7.setText(_translate("MainWindow", "推送文件"))
        self.pushButton_8.setText(_translate("MainWindow", "推送文件夹"))
        self.pushButton_13.setText(_translate("MainWindow", "获取包名"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "包名"))
        self.pushButton_17.setText(_translate("MainWindow", "adb重启"))
        self.pushButton_14.setText(_translate("MainWindow", "缓存clear"))
        self.pushButton_15.setText(_translate("MainWindow", "卸载apk"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.pushButton_19.setText(_translate("MainWindow", "验证码-alpha"))
        self.pushButton_20.setText(_translate("MainWindow", "验证码-pre"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ADB"))
        self.groupBox_4.setTitle(_translate("MainWindow", "monkey"))
        self.label.setText(_translate("MainWindow", "-P"))
        self.label_2.setText(_translate("MainWindow", "-S"))
        self.label_5.setText(_translate("MainWindow", "-T"))
        self.label_4.setText(_translate("MainWindow", "-V"))
        self.label_6.setText(_translate("MainWindow", "-E"))
        self.crashes.setText(_translate("MainWindow", "ignore-crashes"))
        self.timeouts.setText(_translate("MainWindow", "ignore-timeouts"))
        self.security_exceptions.setText(_translate("MainWindow", "ignore-security-exceptions"))
        self.kill_error.setText(_translate("MainWindow", "kill-process-after-error"))
        self.native_crashes.setText(_translate("MainWindow", "monitor-native-crashes"))
        self.label_7.setText(_translate("MainWindow", "点击"))
        self.label_8.setText(_translate("MainWindow", "滑动"))
        self.label_9.setText(_translate("MainWindow", "缩放"))
        self.label_10.setText(_translate("MainWindow", "轨迹"))
        self.pushButton_16.setText(_translate("MainWindow", "停止"))
        self.label_12.setText(_translate("MainWindow", "旋转"))
        self.label_13.setText(_translate("MainWindow", "导航"))
        self.label_14.setText(_translate("MainWindow", "按键"))
        self.label_15.setText(_translate("MainWindow", "活动"))
        self.pushButton_4.setText(_translate("MainWindow", "Monkey"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Monkey"))
        self.groupBox_2.setTitle(_translate("MainWindow", "日志"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Helvetica Neue\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:9pt;\"><br /></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "保存"))
        self.pushButton_10.setText(_translate("MainWindow", "清空"))
        self.pushButton_12.setText(_translate("MainWindow", "查看"))


if __name__ == '__main__':
    QtWidgets.QApplication.setQuitOnLastWindowClosed(False)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
